export const CURRENT_WEATHER_REPO = 'CURRENT_WEATHER_REPO';
export const CURRENT_WEATHER_USECASE = 'CURRENT_WEATHER_USECASE';
export const CURRENT_WEATHER_REMOTE_DATA = 'CURRENT_WEATHER_REMOTE_DATA';

export const ASTRONOMY_REPO = 'ASTRONOMY_REPO';
export const ASTRONOMY_USECASE = 'ASTRONOMY_USECASE';
export const ASTRONOMY_REMOTE_DATA = 'ASTRONOMY_REMOTE_DATA';

export const FORECAST_REPO = 'FORECAST_REPO';
export const FORECAST_USECASE = 'FORECAST_USECASE';
export const FORECAST_REMOTE_DATA = 'FORECAST_REMOTE_DATA';

export const HISTORY_REPO = 'HISTORY_REPO';
export const HISTORY_USECASE = 'HISTORY_USECASE';
export const HISTORY_REMOTE_DATA = 'HISTORY_REMOTE_DATA';

export const LOCATION_REPO = 'LOCATION_REPO';
export const LOCATION_USECASE = 'LOCATION_USECASE';
export const LOCATION_REMOTE_DATA = 'LOCATION_REMOTE_DATA';
