import {scale} from '@core/style';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  containerCurWeather: {
    height: scale(185),
    borderRadius: scale(10),
    marginVertical: 5,
  },
  curWeatherCard: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    overflow: 'hidden',
  },
  iconContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  icon: {
    width: '80%',
    height: '80%',
    borderRadius: scale(100),
  },
  info: {flex: 1, alignItems: 'flex-start', padding: scale(2)},
  dateCard: {flexDirection: 'row'},
  tempCard: {
    flex: 5,
    justifyContent: 'flex-start',
    alignItems: 'center',
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    width: '100%',
    height: '80%',
  },
  tempText: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontSize: scale(55),
  },
  locTimeCard: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  locTime: {
    textAlign: 'center',
    fontSize: scale(10),
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontWeight: '400',
  },
  lastUpdDate: {
    textAlign: 'center',
    fontStyle: 'italic',
    fontSize: scale(10),
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontWeight: '400',
  },
  tempInfoText: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontSize: scale(20),
    alignItems: 'flex-start',
  },
  locCard: {
    flex: 1,
    rowGap: scale(1),
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: scale(5),
    overflow: 'hidden',
  },
  locDate: {
    textAlign: 'left',
    paddingHorizontal: scale(5),
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontWeight: '400',
  },
  locText: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontSize: scale(34),
    fontWeight: '400',
    width: '100%',
  },
  minMaxText: {
    textAlign: 'center',
    color: 'rgba(255, 255, 255, 1)',
    fontFamily: 'Poppins',
    fontSize: scale(20),
    fontWeight: '400',
  },
});
